name: Deploy Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - "worker/**"
      - "workers-config.json"

jobs:
  deploy-workers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Wrangler CLI
        run: npm install -g wrangler

      - name: Deploy all Workers
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          echo "Reading workers-config.json..."
          for row in $(cat worker/workers-config.json | jq -c '.[]'); do
            NAME=$(echo $row | jq -r '.name')
            FOLDER=$(echo $row | jq -r '.folder')
            ACCOUNT_ID=$(echo $row | jq -r '.account_id')
            ENV=$(echo $row | jq -r '.env')

            echo "Deploying $NAME from $FOLDER..."
            cd $FOLDER
            wrangler publish --account-id $ACCOUNT_ID --env $ENV
            cd -
          done
      - name: Confirm Deployment
        run: echo "Cloudflare Workers deployed successfully."